Updating to wcslib-4.8

diff --git a/C/GNUmakefile b/C/GNUmakefile
--- a/C/GNUmakefile
+++ b/C/GNUmakefile
@@ -1,5 +1,5 @@
 #-----------------------------------------------------------------------------
-# GNU makefile for building WCSLIB 4.7 and its test suite.
+# GNU makefile for building WCSLIB 4.8 and its test suite.
 #
 # Summary of the main targets
 # ---------------------------
@@ -13,11 +13,12 @@
 #              library the C source files generated by 'flex'.
 #
 #   check (or test): Compile and run the test programs.  By default they are
-#              executed in batch mode; use
+#              executed in batch mode, and non-graphical tests only report
+#              "PASS" on success.  Use
 #
 #                gmake MODE=interactive check
 #
-#              to run them interactively.
+#              to run them interactively with full diagnostic output.
 #
 #   tests:     Compile the test programs (but don't run them).
 #
@@ -27,7 +28,7 @@
 #
 # Author: Mark Calabretta, Australia Telescope National Facility
 # http://www.atnf.csiro.au/~mcalabre/index.html
-# $Id: GNUmakefile,v 4.7.1.1 2011/02/07 07:04:22 cal103 Exp cal103 $
+# $Id: GNUmakefile,v 4.8 2011/08/15 08:05:53 cal103 Exp $
 #-----------------------------------------------------------------------------
 # Get configure settings.
 include ../makedefs
@@ -64,28 +65,39 @@ ifneq "$(DO_WCSHDR)" ""
 endif
 
 # Test programs that don't require PGPLOT.
-TEST_N := tlin tlog tprj1 tsph tspx ttab1 twcs twcssub tpih1 tbth1 tfitshdr \
-          tunits twcsfix
+TEST_N := tlin tlog tprj1 tsph tsphdpa tspx ttab1 twcs twcssub tpih1 tbth1 \
+          tfitshdr tunits twcsfix
 
-# Test programs that do require PGPLOT.
+# Test programs that require CFITSIO (they don't need PGPLOT).
+TEST_C := twcstab twcshdr
+
+# Test programs that require PGPLOT but not PGSBOX.
 TEST_P := tspc tprj2 tcel1 tcel2 ttab2 ttab3 twcsmix
 
+# Test programs that require PGPLOT and PGSBOX.
+TEST_B := tpih2
+
 # Test programs that aren't automatically exercised.
-TEST_X := tsphdpa
+TEST_X := tsphdpa twcshdr
 
 TESTS  := $(TEST_N)
-ifneq "$(PGPLOTINC)" ""
-ifneq "$(PGPLOTLIB)" ""
-  TESTS   += $(TEST_P) tpih2
+
+# Add test programs that require CFITSIO if we have it.
+ifneq "$(CFITSIOINC)" ""
+ifneq "$(CFITSIOLIB)" ""
+  TESTS += $(TEST_C)
 endif
 endif
 
-# Test programs that require CFITSIO.
-ifneq "$(CFITSIOINC)" ""
-ifneq "$(CFITSIOLIB)" ""
-  TESTS  += twcstab twcshdr
+# Add test programs that require PGPLOT if we have it.
+ifneq "$(PGPLOTINC)" ""
+ifneq "$(PGPLOTLIB)" ""
+  TESTS += $(TEST_P) $(TEST_B)
 endif
 endif
+
+# Remove tests that aren't automatically exercised.
+TESTS := $(filter-out $(TEST_X), $(TESTS))
 
 PGSBOXLIB := ../pgsbox/libpgsbox-$(LIBVER).a
 
@@ -121,6 +133,7 @@ $(PICLIB)(%.o) : %.c
 	-@ $(RM) $@
 	   $(CPP) $(CPPFLAGS) $(CFLAGS) $< > $@
 
+# Print out include file dependencies.
 %.d : %.c
 	-@ echo ''
 	-@ $(CPP) $(CPPFLAGS) $(CFLAGS) $< | \
@@ -131,21 +144,44 @@ $(PICLIB)(%.o) : %.c
 run_% : %
 	-@ echo ''
 	-@ $(TIMER)
-	 @ if [ '$(MODE)' = interactive ] ; then \
+	 @ if [ '$(MODE)' = interactive -o '$(VALGRIND)' ] ; then \
 	     printf 'Press <CR> to run $<: ' ; \
 	     read DUMMY ; \
 	     if [ '$<' = tunits ] ; then \
 	       $(VALGRIND) ./$< < test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
+	     else \
 	       $(VALGRIND) ./$< ; \
 	     fi ; \
 	   else \
 	     if [ '$<' = tcel2 ] ; then \
-	       echo N | $(VALGRIND) ./$< ; \
-	     elif [ '$<' = tunits ] ; then \
-	       $(VALGRIND) ./$< < test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
-	       $(VALGRIND) ./$< < /dev/null 2>&1 ; \
+	       echo N | ./$< ; \
+	     elif [ '$(filter $<, $(TEST_N) $(TEST_C))' ] ; then \
+	       if [ '$<' = tunits ] ; then \
+	         ./$< < test/units_test > $<.out 2>&1 ; \
+	       else \
+	         ./$< < /dev/null > $<.out 2>&1 ; \
+	       fi ; \
+	       if grep 'PASS:' $<.out > /dev/null ; then \
+	         head -2 $<.out ; \
+	         grep 'PASS:' $<.out ; \
+	       elif [ -f 'test/$<.out' ] ; then \
+	         trap 'rm -f run_test.tmp' 0 1 2 3 15 ; \
+	         sed -e 's/0x[0-9a-f][0-9a-f][0-9a-f]*/0x<address>/g' $<.out > \
+	           run_test.tmp ; \
+	         mv -f run_test.tmp $<.out ; \
+	         if cmp -s $<.out test/$<.out ; then \
+	           head -2 $<.out ; \
+	           echo 'PASS: Output agrees with C/test/$<.out' ; \
+	         else \
+	           cat $<.out ; \
+	           echo '' ; \
+	           echo 'FAIL: Output disagrees with C/test/$<.out' ; \
+	         fi ; \
+	       else \
+	         cat $<.out ; \
+	       fi ; \
+	     else \
+	       ./$< < /dev/null 2>&1 ; \
 	     fi ; \
 	   fi
 	-@ echo ''
@@ -203,9 +239,10 @@ install : build
 	   $(LN_S) $(notdir $(INCDIR)) $(INCLINK)
 
 clean :
-	- $(RM) -r *.o *.i a.out core *.dSYM $(EXTRA_CLEAN)
+	- $(RM) -r *.o *.i a.out t*.out core *.dSYM $(EXTRA_CLEAN)
 
 cleaner : clean
+	-  $(RM) .gdb_history
 	-  $(RM) $(TEST_N) $(TEST_X)
 	-  $(RM) $(TEST_P) tpih2 twcstab twcshdr
 	-  $(RM) tofits bth.fits pih.fits wcstab.fits
@@ -218,9 +255,9 @@ cleanest distclean realclean : cleaner
 
 check test : tests $(TESTS:%=run_%)
 
-tests : $(TESTS)
+tests : $(TESTS) $(TEST_X)
 
-$(TEST_N) $(TEST_X) : % : test/%.c $(WCSLIB)
+$(TEST_N) : % : test/%.c $(WCSLIB)
 	-@ echo ''
 	   $(CC) $(CPPFLAGS) $(CFLAGS) $(LDFLAGS) -o $@ $< $(WCSLIB) $(LIBS)
 	-@ $(RM) $@.o
@@ -292,64 +329,74 @@ show ::
 	-@ -@ echo '  FLEXMODS    := $(FLEXMODS)'
 	-@ -@ echo '  MODULES     := $(MODULES)'
 
-# Dependencies
-#-------------
+# Dependencies (use the %.d pattern rule to list them)
+#-----------------------------------------------------
 
-$(WCSLIB)(cel.o)      : cel.h prj.h sph.h wcserr.h wcsmath.h wcsprintf.h \
-	                wcstrig.h
+$(WCSLIB)(cel.o)      : cel.h prj.h sph.h wcsconfig.h wcserr.h wcsmath.h \
+                        wcsprintf.h wcstrig.h
 $(WCSLIB)(fitshdr.o)  : wcsconfig.h fitshdr.h
 $(WCSLIB)(lin.o)      : lin.h wcserr.h wcsprintf.h
 $(WCSLIB)(log.o)      : log.h
-$(WCSLIB)(prj.o)      : prj.h wcserr.h wcsmath.h wcsprintf.h wcstrig.h
-$(WCSLIB)(spc.o)      : spc.h spx.h wcserr.h wcsmath.h wcsprintf.h wcstrig.h
-$(WCSLIB)(sph.o)      : sph.h wcstrig.h
-$(WCSLIB)(spx.o)      : spx.h wcserr.h
+$(WCSLIB)(prj.o)      : prj.h wcsconfig.h wcserr.h wcsmath.h wcsprintf.h \
+                        wcstrig.h wcsutil.h
+$(WCSLIB)(spc.o)      : spc.h spx.h wcserr.h wcsmath.h wcsprintf.h wcstrig.h \
+                        wcsutil.h
+$(WCSLIB)(sph.o)      : sph.h wcsconfig.h wcstrig.h
+$(WCSLIB)(spx.o)      : spx.h wcserr.h wcsmath.h
 $(WCSLIB)(tab.o)      : tab.h wcserr.h wcsmath.h wcsprintf.h
 $(WCSLIB)(wcs.o)      : cel.h lin.h log.h prj.h spc.h sph.h spx.h tab.h \
-                        wcs.h wcserr.h wcsmath.h wcstrig.h wcsprintf.h \
-			wcsunits.h wcsutil.h
+                        wcs.h wcsconfig.h wcserr.h wcsmath.h wcsprintf.h \
+                        wcstrig.h wcsunits.h wcsutil.h
 $(WCSLIB)(wcsbth.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
-			wcshdr.h wcsmath.h
+                        wcshdr.h wcsmath.h
+$(WCSLIB)(wcserr.o)   : wcserr.h wcsprintf.h
 $(WCSLIB)(wcsfix.o)   : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h \
-                        wcserr.h wcsfix.h wcsmath.h wcsunits.h
+                        wcserr.h wcsfix.h wcsmath.h wcsunits.h wcsutil.h
 $(WCSLIB)(wcshdr.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
-			wcshdr.h wcsutil.h
+                        wcshdr.h wcsmath.h wcsutil.h
 $(WCSLIB)(wcspih.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h \
-			wcshdr.h wcsmath.h
+                        wcshdr.h wcsmath.h
 $(WCSLIB)(wcsprintf.o): wcsprintf.h
-$(WCSLIB)(wcstrig.o)  : wcsmath.h wcstrig.h
+$(WCSLIB)(wcstrig.o)  : wcsconfig.h wcsmath.h wcstrig.h
 $(WCSLIB)(wcsulex.o)  : wcserr.h wcsmath.h wcsunits.h
 $(WCSLIB)(wcsunits.o) : wcserr.h wcsunits.h
 $(WCSLIB)(wcsutil.o)  : wcsutil.h
 $(WCSLIB)(wcsutrn.o)  : wcserr.h wcsunits.h
 
-tbth1 tbth1_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcsfix.h wcshdr.h
-tcel1   : cel.h prj.h
-tcel2   : cel.h prj.h
-tfitshdr tfitshdr_cfitsio : wcsconfig.h wcsconfig_tests.h fitshdr.h
-tlin    : lin.h
+tbth1 tbth1_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h
+tcel1   : cel.h prj.h wcserr.h
+tcel2   : cel.h prj.h wcserr.h
+tfitshdr tfitshdr_cfitsio : fitshdr.h wcsconfig.h wcsconfig_tests.h
+tlin    : lin.h wcserr.h
 tlog    : log.h
-tpih1 tpih1_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcsfix.h wcshdr.h wcsprintf.h
-tpih2 tpih2_cfitsio : cel.h wcsconfig.h wcsconfig_tests.h lin.h prj.h spc.h \
-                      spx.h tab.h wcs.h wcshdr.h
-tprj1   : prj.h wcstrig.h
-tprj2   : prj.h
-tspc    : spc.h spx.h wcstrig.h
-tsph    : sph.h wcstrig.h
-tsphdpa : sph.h wcstrig.h
-tspx    : spx.h
-ttab1   : tab.h
-ttab2   : tab.h
-ttab3   : prj.h tab.h
-tunits  : wcsunits.h
-twcs    : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h
-twcsfix : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsfix.h wcsunits.h
-twcshdr : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h
-twcsmix : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h
-twcssub : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h
-twcstab : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcshdr.h
+tpih1 tpih1_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h wcsprintf.h
+tpih2 tpih2_cfitsio : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcsconfig.h \
+                      wcsconfig_tests.h wcserr.h wcshdr.h
+tprj1   : prj.h wcsconfig.h wcserr.h wcstrig.h
+tprj2   : prj.h wcserr.h
+tspc    : spc.h spx.h wcsconfig.h wcserr.h wcstrig.h
+tsph    : sph.h wcsconfig.h wcstrig.h
+tsphdpa : sph.h
+tspx    : spx.h wcserr.h
+ttab1   : tab.h wcserr.h
+ttab2   : tab.h wcserr.h
+ttab3   : prj.h tab.h wcserr.h
+tunits  : wcserr.h wcsunits.h
+twcs    : cel.h lin.h log.h prj.h spc.h sph.h spx.h tab.h wcs.h wcsconfig.h \
+          wcsconfig_tests.h wcserr.h wcsfix.h wcshdr.h wcslib.h wcsmath.h \
+          wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
+twcsfix : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h wcsfix.h \
+          wcsunits.h
+twcshdr : cel.h fitshdr.h getwcstab.h lin.h log.h prj.h spc.h sph.h spx.h \
+          tab.h wcs.h wcsconfig.h wcserr.h wcsfix.h wcshdr.h wcslib.h \
+          wcsmath.h wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
+twcsmix : cel.h lin.h prj.h spc.h sph.h spx.h tab.h wcs.h wcserr.h
+twcssub : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h wcserr.h
+twcstab : cel.h fitshdr.h getwcstab.h lin.h log.h prj.h spc.h sph.h spx.h \
+          tab.h wcs.h wcsconfig.h wcserr.h wcsfix.h wcshdr.h wcslib.h \
+          wcsmath.h wcsprintf.h wcstrig.h wcsunits.h wcsutil.h
 
 run_tbth1 run_tbth1_cfitsio : bth.fits
 run_tfitshdr run_tfitshdr_cfitsio : pih.fits
diff --git a/Fortran/GNUmakefile b/Fortran/GNUmakefile
--- a/Fortran/GNUmakefile
+++ b/Fortran/GNUmakefile
@@ -1,5 +1,5 @@
 #-----------------------------------------------------------------------------
-# GNU makefile for building the WCSLIB 4.7 FORTRAN wrappers.
+# GNU makefile for building the WCSLIB 4.8 FORTRAN wrappers.
 #
 # Summary of the main targets
 # ---------------------------
@@ -13,11 +13,12 @@
 #              object library.
 #
 #   check (or test): Compile and run the test programs.  By default they are
-#              executed in batch mode; use
+#              executed in batch mode, and non-graphical tests only report
+#              "PASS" on success.  Use
 #
 #                gmake MODE=interactive check
 #
-#              to run them interactively.
+#              to run them interactively with full diagnostic output.
 #
 #   tests:     Compile the test programs (but don't run them).
 #
@@ -25,7 +26,7 @@
 #   1) If you need to make changes then preferably modify ../makedefs.in
 #      instead and re-run configure.
 #
-#   2) This makefile assumes that the WCSLIB 4.7 sources reside in ../C
+#   2) This makefile assumes that the WCSLIB 4.8 sources reside in ../C
 #      (as in the distribution kit).
 #
 #   3) twcstab assumes that ../C/wcstab.fits has already been generated by
@@ -33,7 +34,7 @@
 #
 # Author: Mark Calabretta, Australia Telescope National Facility
 # http://www.atnf.csiro.au/~mcalabre/index.html
-# $Id: GNUmakefile,v 4.7.1.1 2011/02/07 07:04:23 cal103 Exp cal103 $
+# $Id: GNUmakefile,v 4.8 2011/08/15 08:05:54 cal103 Exp $
 #-----------------------------------------------------------------------------
 # Get configure settings.
 include ../makedefs
@@ -65,20 +66,28 @@ vpath %.in ..
 TEST_N := tlin tlog tprj1 tsph tspx ttab1 twcs twcssub tpih1 tfitshdr tunits \
           twcsfix
 
-# Test programs that do require PGPLOT.
+# Test programs that require CFITSIO (they don't need PGPLOT).
+TEST_C := twcstab
+
+# Test programs that require PGPLOT but not PGSBOX.
 TEST_P := tspc tprj2 tcel1 ttab2 ttab3 twcsmix
 
+# Test programs that require PGPLOT and PGSBOX.
+TEST_B := tpih2
+
 TESTS  := $(TEST_N)
-ifneq "$(PGPLOTINC)" ""
-ifneq "$(PGPLOTLIB)" ""
-  TESTS   += $(TEST_P) tpih2
+
+# Add test programs that require CFITSIO if we have it.
+ifneq "$(CFITSIOINC)" ""
+ifneq "$(CFITSIOLIB)" ""
+  TESTS  += $(TEST_C)
 endif
 endif
 
-# Test programs that require CFITSIO.
-ifneq "$(CFITSIOINC)" ""
-ifneq "$(CFITSIOLIB)" ""
-TESTS  += twcstab
+# Add test programs that require PGPLOT if we have it.
+ifneq "$(PGPLOTINC)" ""
+ifneq "$(PGPLOTLIB)" ""
+  TESTS   += $(TEST_P) $(TEST_B)
 endif
 endif
 
@@ -131,18 +140,41 @@ $(PICLIB)(%.o) : %.f
 run_% : %
 	-@ echo ''
 	-@ $(TIMER)
-	 @ if [ '$(MODE)' = interactive ] ; then \
+	 @ if [ '$(MODE)' = interactive -o '$(VALGRIND)' ] ; then \
 	     printf 'Press <CR> to run $<: ' ; \
 	     read DUMMY ; \
 	     if [ '$<' = tunits ] ; then \
-	       ./$< < ../C/test/units_test ; \
+	       $(VALGRIND) ./$< < test/units_test ; \
 	     else \
-	       ./$< ; \
+	       $(VALGRIND) ./$< ; \
 	     fi ; \
 	   else \
-	     if [ '$<' = tunits ] ; then \
-	       ./$< < ../C/test/units_test ; \
-	     elif [ '$<' != twcshdr ] ; then \
+	     if [ '$(filter $<, $(TEST_N) $(TEST_C))' ] ; then \
+	       if [ '$<' = tunits ] ; then \
+	         ./$< < ../C/test/units_test > $<.out 2>&1 ; \
+	       else \
+	         ./$< < /dev/null > $<.out 2>&1 ; \
+	       fi ; \
+	       if grep 'PASS:' $<.out > /dev/null ; then \
+	         head -2 $<.out ; \
+	         grep 'PASS:' $<.out ; \
+	       elif [ -f 'test/$<.out' ] ; then \
+	         trap 'rm -f run_test.tmp' 0 1 2 3 15 ; \
+	         sed -e 's/0x[0-9a-f][0-9a-f][0-9a-f]*/0x<address>/g' $<.out > \
+	           run_test.tmp ; \
+	         mv -f run_test.tmp $<.out ; \
+	         if cmp -s $<.out test/$<.out ; then \
+	           head -2 $<.out ; \
+	           echo 'PASS: Output agrees with Fortran/test/$<.out' ; \
+	         else \
+	           cat $<.out ; \
+	           echo '' ; \
+	           echo 'FAIL: Output disagrees with Fortran/test/$<.out' ; \
+	         fi ; \
+	       else \
+	         cat $<.out ; \
+	       fi ; \
+	     else \
 	       ./$< < /dev/null 2>&1 ; \
 	     fi ; \
 	   fi
@@ -183,9 +215,10 @@ install : build
 	$(INSTALL) -m 444 *.inc $(INCDIR)
 
 clean :
-	-  $(RM) -r *.o *.i a.out core fort.* *.dSYM $(EXTRA_CLEAN)
+	-  $(RM) -r *.o *.i a.out t*.out core fort.* *.dSYM $(EXTRA_CLEAN)
 
 cleaner : clean
+	-  $(RM) .gdb_history
 	-  $(RM) $(TEST_N)
 	-  $(RM) $(TEST_P) tpih2 twcstab
 	-  $(RM) tofits pih.fits
@@ -248,33 +281,33 @@ GNUmakefile : ../makedefs ;
 show ::
 	-@ echo '  MODULES     := $(MODULES)'
 
-# Dependencies
-#-------------
+# Dependencies (use the %.d pattern rule to list them)
+#-----------------------------------------------------
 
-$(WCSLIB)(cel_f.o)      : cel.h wcsconfig.h wcsconfig_f77.h prj.h
-$(WCSLIB)(fitshdr_f.o)  : wcsconfig.h wcsconfig_f77.h fitshdr.h wcsutil.h
-$(WCSLIB)(getwcstab_f.o): wcsconfig.h wcsconfig_f77.h getwcstab.h
-$(WCSLIB)(lin_f.o)      : wcsconfig.h wcsconfig_f77.h lin.h
-$(WCSLIB)(log_f.o)      : wcsconfig.h wcsconfig_f77.h log.h
-$(WCSLIB)(prj_f.o)      : wcsconfig.h wcsconfig_f77.h prj.h
-$(WCSLIB)(spc_f.o)      : wcsconfig.h wcsconfig_f77.h spc.h spx.h wcsutil.h
-$(WCSLIB)(sph_f.o)      : wcsconfig.h wcsconfig_f77.h sph.h
-$(WCSLIB)(spx_f.o)      : wcsconfig.h wcsconfig_f77.h spx.h
-$(WCSLIB)(tab_f.o)      : wcsconfig.h wcsconfig_f77.h tab.h
-$(WCSLIB)(wcs_f.o)      : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcsutil.h
-$(WCSLIB)(wcsfix_f.o)   : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcsfix.h
-$(WCSLIB)(wcshdr_f.o)   : cel.h wcsconfig.h wcsconfig_f77.h lin.h prj.h \
-                          spc.h spx.h tab.h wcs.h wcshdr.h
-$(WCSLIB)(wcsunits_f.o) : wcsconfig.h wcsconfig_f77.h wcsunits.h wcsutil.h
+$(WCSLIB)(cel_f.o)      : cel.h prj.h wcserr.h wcsconfig_f77.h
+$(WCSLIB)(fitshdr_f.o)  : fitshdr.h wcsconfig.h wcsconfig_f77.h wcsutil.h
+$(WCSLIB)(getwcstab_f.o): getwcstab.h wcsconfig_f77.h
+$(WCSLIB)(lin_f.o)      : lin.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(log_f.o)      : log.h wcsconfig_f77.h
+$(WCSLIB)(prj_f.o)      : prj.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(spc_f.o)      : spc.h spx.h wcsconfig_f77.h wcserr.h wcsutil.h
+$(WCSLIB)(sph_f.o)      : sph.h wcsconfig_f77.h
+$(WCSLIB)(spx_f.o)      : spx.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(tab_f.o)      : tab.h wcsconfig_f77.h wcserr.h
+$(WCSLIB)(wcs_f.o)      : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcsutil.h
+$(WCSLIB)(wcsfix_f.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcsfix.h
+$(WCSLIB)(wcshdr_f.o)   : cel.h lin.h prj.h spc.h spx.h tab.h wcs.h \
+                          wcsconfig_f77.h wcserr.h wcshdr.h
+$(WCSLIB)(wcsunits_f.o) : wcsconfig_f77.h wcserr.h wcsunits.h wcsutil.h
 
 tcel1   : cel.inc prj.inc
-tfitshdr: fitshdr.inc pih.fits
+tfitshdr: fitshdr.inc wcshdr.inc
 tlin    : lin.inc
 tlog    : log.inc
-tpih1   : wcs.inc wcshdr.inc pih.fits
-tpih2   : wcs.inc wcshdr.inc pih.fits
+tpih1   : wcs.inc wcsfix.inc wcshdr.inc
+tpih2   : wcs.inc wcshdr.inc
 tprj1   : prj.inc
 tprj2   : prj.inc
 tspc    : spc.inc spx.inc
@@ -283,11 +316,11 @@ ttab1   : tab.inc
 ttab2   : tab.inc
 ttab3   : prj.inc tab.inc
 tunits  : wcsunits.inc
-twcs    : cel.inc prj.inc wcs.inc
-twcsfix : wcs.inc
+twcs    : cel.inc prj.inc wcs.inc wcserr.inc wcsmath.inc
+twcsfix : wcs.inc wcsfix.inc wcsunits.inc
 twcsmix : cel.inc lin.inc prj.inc wcs.inc
-twcssub : cel.inc prj.inc wcs.inc
-twcstab : wcs.inc wcshdr.inc
+twcssub : wcs.inc
+twcstab : getwcstab.inc wcs.inc wcsfix.inc wcshdr.inc
 
 run_tfitshdr run_tpih1 run_tpih2: pih.fits
 run_twcstab: ../C/wcstab.fits
